### ISSUE TITLE
Save Console Errors

### ISSUE THREAD

**Issue by risamaki** [risamaki/ChromeOverflow#12]

**Comment by wongvincent** [comment]
https://github.com/risamaki/ChromeOverflow/commit/0c48112001bc64fdd71ac67f1ca7f52a18be6370
https://github.com/risamaki/ChromeOverflow/commit/b3e76ae2e1474ef7d8bddd0a4347f277a9360313
https://github.com/risamaki/ChromeOverflow/commit/bbe4fba6decebfc66899d0550cc66a60675cc226
